image: mesosphere/aws-cli

pipelines:
  tags:
    '**':
      - step:
          name: Build and publish
          script:
            - eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            - docker build -t $AWS_REGISTRY_URL:$BITBUCKET_BUILD_NUMBER .
            - docker tag $AWS_REGISTRY_URL:$BITBUCKET_BUILD_NUMBER $AWS_REGISTRY_URL:$BITBUCKET_TAG
            - docker push $AWS_REGISTRY_URL:$BITBUCKET_TAG

options:
  docker: True
